### ISSUE TITLE
Better use `const` for magic numbers (also better to capitlize var in consistency)

### ISSUE THREAD

**Issue by keyi6** [CSCI-526/spring-2024-project-tuesday-it-takes-six#1]
https://github.com/CSCI-526/spring-2024-project-tuesday-it-takes-six/blob/f1d0b186ba2890bd45b24161309c44fc4b44adb9/Assets/Scripts/ButtonController.cs#L11

**Comment by OfferPlease** [comment]
A Vector3 cannot be set to const. Maybe change it to SerializeField
