### ISSUE TITLE
Need a `util` class for these functions which may be needed in multiple files

### ISSUE THREAD

**Issue by keyi6** [CSCI-526/spring-2024-project-tuesday-it-takes-six#2]
https://github.com/CSCI-526/spring-2024-project-tuesday-it-takes-six/blob/f2662a995f07293d8d5dcd66c37332b9a6d7f080/Assets/Scripts/LaserLauncherControll.cs#L31

https://github.com/CSCI-526/spring-2024-project-tuesday-it-takes-six/blob/f2662a995f07293d8d5dcd66c37332b9a6d7f080/Assets/Scripts/EnemyController.cs#L60

@Jinjing-Li fyi i'm going to move your code if it's okay

**Comment by Jinjing-Li** [comment]
Sure.

**Comment by keyi6** [comment]
Done be23d1f5f7839f7e178a8f5c4ef7a1931a90822c
